# dbxtool
# Autogenerated from man page /usr/share/man/man1/dbxtool.1.gz
complete -c dbxtool -l dbx -d 'Use a specified file for dbx rather than the system variable'
complete -c dbxtool -l list -d 'List DBX entries in the system database, or in a copy of it or an update file'
complete -c dbxtool -l verbose -d 'Show a bunch of verbose output about what dbxtool is doing'
complete -c dbxtool -l apply -d 'Apply updates specified on the command line.   Does not work with --dbx'

