# geoipupdate
# Autogenerated from man page /usr/share/man/man1/geoipupdate.1.gz
complete -c geoipupdate -s d -l database-directory -d 'Install databases to a custom directory.  This is optional'
complete -c geoipupdate -s f -l config-file -d 'The configuration file to use.  See GeoIP'
complete -c geoipupdate -s h -l help -d 'Display help and exit'
complete -c geoipupdate -l stack-trace -d 'Show a stack trace on any error message'
complete -c geoipupdate -s V -l version -d 'Display version information and exit'
complete -c geoipupdate -s v -l verbose -d 'Enable verbose mode.  Prints out the steps that geoipupdate takes'

