# git-revise
# Autogenerated from man page /usr/share/man/man1/git-revise.1.gz
complete -c git-revise -s a -l all -d 'Stage changes to tracked files before revising'
complete -c git-revise -s p -l patch -d 'Interactively stage hunks from the worktree before revising'
complete -c git-revise -l no-index -d 'Ignore staged changes in the index'
complete -c git-revise -l reauthor -d 'Reset target commit\\(aqs author to the current user'
complete -c git-revise -l ref -d 'Working branch to update; defaults to HEAD'
complete -c git-revise -s S -l gpg-sign -l no-gpg-sign -d 'GPG-sign commits.   Overrides both the commit. gpgSign and revise'
complete -c git-revise -s i -l interactive -d 'Rather than applying staged changes to <target>, edit a todo list of actions …'
complete -c git-revise -l autosquash -l no-autosquash -d 'Rather than directly applying staged changes to <target>, automatically perfo…'
complete -c git-revise -s c -l cut -d 'Interactively select hunks from <target>'
complete -c git-revise -s e -l edit -d 'After applying staged changes, edit <target>\\(aqs commit message'
complete -c git-revise -s m -l message -d 'Use the given <msg> as the new commit message for <target>'
complete -c git-revise -l version -d 'Print version information and exit'

