# obxprop
# Autogenerated from man page /usr/share/man/man1/obxprop.1.gz
complete -c obxprop -l help -d 'Show a summary of the options available'
complete -c obxprop -l display -d 'Specify the X display to use'

