# rmiregistry-openjdk19
# Autogenerated from man page /usr/share/man/man1/rmiregistry-openjdk19.1.gz
complete -c rmiregistry-openjdk19 -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry-openjdk19 -s J -s J -d 'Java interpreter'

