# tint2
# Autogenerated from man page /usr/share/man/man1/tint2.1.gz
complete -c tint2 -l version -d 'Prints version information and exits'
complete -c tint2 -s c -d 'Specifies which configuration file to use instead of the default'
complete -c tint2 -s v -d 'Prints version information and exits'
complete -c tint2 -s h -l help -d 'Display this help and exits.  CONFIGURATION Table of contents'

